[package]
name = "fnum-derive"
version = "0.0.1"
authors = ["carrotflakes <carrotflakes@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.8"
syn = { version = "1.0.14", features = ["full", "extra-traits"] }
